import { Base } from "./Base";

export class Address extends Base {
	static className: string = "Address";

	constructor() {
		super();
		this._fields = [
			{
				name: "@id",
				type: "string",
				representedType: "string",
				primary: true,
				unique: true,
				notNull: true,
				required: true,
				semiRequired: false,
			},
			{
				name: "ic:hasStreet",
				displayName: "hasStreet",
				type: "text",
				representedType: "string",
				defaultValue: "",
				unique: false,
				notNull: false,
				required: false,
				semiRequired: false,
			},
			{
				name: "ic:hasStreetType",
				displayName: "hasStreetType",
				type: "select",
				selectOptions: [
					"ic:avenue",
					"ic:boulevard",
					"ic:circle",
					"ic:crescent",
					"ic:drive",
					"ic:road",
					"ic:street",
				],
				representedType: "string",
				defaultValue: "",
				unique: false,
				notNull: false,
				required: false,
				semiRequired: false,
			},
			{
				name: "ic:hasStreetNumber",
				displayName: "hasStreetNumber",
				type: "string",
				representedType: "string",
				defaultValue: "",
				unique: false,
				notNull: false,
				required: false,
				semiRequired: false,
			},
			{
				name: "ic:hasStreetDirection",
				displayName: "hasStreetDirection",
				type: "select",
				selectOptions: ["ic:east", "ic:north", "ic:south", "ic:west"],
				representedType: "string",
				defaultValue: "",
				unique: false,
				notNull: false,
				required: false,
				semiRequired: false,
			},
			{
				name: "ic:hasUnitNumber",
				displayName: "hasUnitNumber",
				type: "string",
				representedType: "string",
				defaultValue: "",
				unique: false,
				notNull: false,
				required: false,
				semiRequired: false,
			},
			{
				name: "ic:hasCity",
				displayName: "hasCity",
				type: "text",
				representedType: "string",
				defaultValue: "",
				unique: false,
				notNull: false,
				required: false,
				semiRequired: false,
			},
			{
				name: "ic:hasProvince",
				displayName: "hasProvince",
				type: "text",
				representedType: "string",
				defaultValue: "",
				unique: false,
				notNull: false,
				required: false,
				semiRequired: false,
			},
			{
				name: "ic:hasPostalCode",
				displayName: "hasPostalCode",
				type: "text",
				representedType: "string",
				defaultValue: "",
				unique: false,
				notNull: false,
				required: false,
				semiRequired: false,
			},
			{
				name: "ic:hasCountry",
				displayName: "hasCountry",
				type: "text",
				representedType: "string",
				defaultValue: "",
				unique: false,
				notNull: false,
				required: false,
				semiRequired: false,
			},
		];
	}
}
